package timsitu.components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import timsitu.events.EventMenuSelected;
import timsitu.models.Menu;
import timsitu.models.User;
import timsitu.models.UserSessions;

public class MenuComponent extends javax.swing.JPanel {
    
    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected event) {
        this.event = event;
        listMenu1.addEventMenuSelected(event);
    }

    public MenuComponent() {
        initComponents();
        
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }
    
    
    
    private void init() {
        
        if(UserSessions.getRole() == User.EnumRole.ADMIN){
            listMenu1.addItem(new Menu("0", "Dashboard", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("1", "Pendaftaran", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("2", "Transaksi", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("3", "Jadwal Dokter", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("4", " ", Menu.EnumMenuType.EMPTY));

            listMenu1.addItem(new Menu("5", "Data Master", Menu.EnumMenuType.TITLE));
            listMenu1.addItem(new Menu("6", " ", Menu.EnumMenuType.EMPTY));
            listMenu1.addItem(new Menu("7", "Pasien", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("8", "Dokter", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("9", "Apoteker", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("10", "Obat", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("11", "Poliklinik", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("12", " ", Menu.EnumMenuType.EMPTY));

            listMenu1.addItem(new Menu("13", "Akun", Menu.EnumMenuType.TITLE));
            listMenu1.addItem(new Menu("14", " ", Menu.EnumMenuType.EMPTY));
            listMenu1.addItem(new Menu("15", "Logout", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("16", "", Menu.EnumMenuType.EMPTY));
            
        }else if(UserSessions.getRole() == User.EnumRole.DOKTER){
            listMenu1.addItem(new Menu("0", "Dashboard", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("1", "Pemeriksaan", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("2", " ", Menu.EnumMenuType.EMPTY));
            
            listMenu1.addItem(new Menu("3", "Akun", Menu.EnumMenuType.TITLE));
            listMenu1.addItem(new Menu("4", " ", Menu.EnumMenuType.EMPTY));
            listMenu1.addItem(new Menu("5", "Logout", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("6", "", Menu.EnumMenuType.EMPTY));
            
        }else if(UserSessions.getRole() == User.EnumRole.APOTEKER){
            listMenu1.addItem(new Menu("0", "Dashboard", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("1", "Data Obat", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("2", "Pengambilan Obat", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("3", " ", Menu.EnumMenuType.EMPTY));
            
            listMenu1.addItem(new Menu("4", "Akun", Menu.EnumMenuType.TITLE));
            listMenu1.addItem(new Menu("5", " ", Menu.EnumMenuType.EMPTY));
            listMenu1.addItem(new Menu("6", "Logout", Menu.EnumMenuType.MENU));
            listMenu1.addItem(new Menu("7", "", Menu.EnumMenuType.EMPTY));
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new timsitu.customs.ListMenu<>();

        panelMoving.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timsitu/images/logo.png"))); // NOI18N
        jLabel1.setText("SIMRS");
        jLabel1.setSize(new java.awt.Dimension(34, 34));

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gradien = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(gradien);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintChildren(g);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private timsitu.customs.ListMenu<String> listMenu1;
    private javax.swing.JPanel panelMoving;
    // End of variables declaration//GEN-END:variables
}
