package timsitu.pages.pemeriksaan;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import timsitu.events.TableActionEvent;
import timsitu.models.Pemeriksaan;
import timsitu.models.Reservasi;
import timsitu.models.SingleActionButtonEditor;
import timsitu.models.SingleActionButtonRender;
import timsitu.models.UserSessions;
import timsitu.pages.*;
import timsitu.pages.obat.FormObatPage;

public class PemeriksaanPage extends javax.swing.JPanel {
    ArrayList<Reservasi> dataReservasi;
    Pemeriksaan pemeriksaan = null;

    public PemeriksaanPage() {
        
        initComponents();
        
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {}

            @Override
            public void onDelete(int row) {}

            @Override
            public void onClick(int row) {
                pemeriksaan = Pemeriksaan.getDataByReservasi(dataReservasi.get(row).getKode());
                MainPage.setForm(new FormPemeriksaanPage(pemeriksaan, dataReservasi.get(row)));
            }
        };
        
        tblPameriksaan.getColumnModel().getColumn(6).setCellRenderer(new SingleActionButtonRender("Periksa"));
        tblPameriksaan.getColumnModel().getColumn(6).setCellEditor(new SingleActionButtonEditor(event, "Periksa"));
        
        showData();
    }
    
    private void showData(){
        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel)tblPameriksaan.getModel();
        tableModel.getDataVector().removeAllElements();
        
        dataReservasi = Reservasi.getAllData(UserSessions.getUserId());
        
        int no = 1;
        
        for (Reservasi data : dataReservasi) {
            tableModel.addRow(new Object[]{
                no++,
                data.getPasien().getKode(),
                data.getPasien().getNama(),
                data.getPasien().getJenisKelamin().toString(),
                data.getNoAntrian(),
                data.getStatus()
            });
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new timsitu.customs.PanelBorder();
        spTable = new javax.swing.JScrollPane();
        tblPameriksaan = new timsitu.customs.Table();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(829, 508));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setPreferredSize(new java.awt.Dimension(829, 508));

        spTable.setBorder(null);
        spTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblPameriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Pasien", "Nama Pasien", "Jenis Kelamin", "No Antrian", "Status", "Aksi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(tblPameriksaan);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Data Reservasi");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 641, Short.MAX_VALUE))
                    .addComponent(spTable))
                .addGap(30, 30, 30))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private timsitu.customs.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private timsitu.customs.Table tblPameriksaan;
    // End of variables declaration//GEN-END:variables
}
